### ISSUE TITLE
XAML Designer stops working if the view contains any SVG content.

### ISSUE THREAD

**Issue by unvestigate** [wieslawsoltes/Svg.Skia#138]
I am using Avalonia 11.0.0 Preview 4 and Svg.Skia via the Avalonia.Svg nuget package, also version 11.0.0 Preview 4. The XAML designer stops working, showing old data or no data at all as soon as Svg content is added to the view. This happens both in Rider 2022.3 and VS2022. Here is a simple UC which exhibits the problem.

```
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
			 xmlns:viewModels="clr-namespace:ArkNet.ViewModels"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="ArkNet.Views.SplashScreenView">
	<Design.DataContext>
		<viewModels:SplashScreenViewModel />
	</Design.DataContext>
	
	<Svg Name="logoSvg" Path="/Assets/logo_cropped.svg" Opacity="0.15"
		 VerticalAlignment="Bottom" HorizontalAlignment="Right" Width="300" />
</UserControl>
```

Here is the SVG file, if that matters:

![logo_cropped](https://user-images.githubusercontent.com/20167696/208291987-8fdfebd0-e870-4ee7-b0a3-87afded6ae9d.svg)

At runtime, the SVG content seems to behave and show up properly. As soon as the Svg element is removed or commented out the designer stars working again (Sometimes it seems to need a rebuild of the project).

**Comment by unvestigate** [comment]
I looked in the designer log in Rider for any errors related to this but nothing seems to come up. I occasionally see this in the log:

```
System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.ReadExact(Byte[] buffer) in /_/src/Avalonia.Remote.Protocol/BsonStreamTransport.cs:line 59
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.Reader() in /_/src/Avalonia.Remote.Protocol/BsonStreamTransport.cs:line 71
```

However, that exception seems to be thrown even if all Svg content is removed, so would seem to be unrelated.

**Comment by unvestigate** [comment]
Allright, now I can close this for real. This turned out to be my mistake and it was the xmlns (ie. namespace) which I had gotten incorrectly set up. In some views I had it incorrect, while in others it was missing completely. You can see from the above code that it is missing. The designer barfed on this, while interestingly the application itself rendered the SVG content properly, even without the namespace set up. Setting it up correctly, eg. like `xmlns:svg="clr-namespace:Avalonia.Svg;assembly=Avalonia.Svg"`
the designer now works properly. I hope this is of help if someone else has similar issues.
