### ISSUE TITLE
Broken on latest Avalonia master

### ISSUE THREAD

**Issue by squidink7** [wieslawsoltes/Svg.Skia#139]
When using the latest nightly builds from Avalonia, any apps using this library crash on launch with an error such as the one below:
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Avalonia.Svg.SvgImage' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Avalonia.StyledProperty`1<!!1> Avalonia.AvaloniaProperty.Register(System.String, !!1, Boolean, Avalonia.Data.BindingMode, System.Func`2<!!1,Boolean>, System.Func`3<Avalonia.IAvaloniaObject,!!1,!!1>, System.Action`2<Avalonia.IAvaloniaObject,Boolean>)'.
   --- End of inner exception stack trace ---
   at Avalonia.Svg.SvgImage.set_Source(SvgSource value) in /_/src/Avalonia.Svg/SvgImage.cs:line 32
   at Avalonia.Svg.SvgImageExtension.ProvideValue(IServiceProvider serviceProvider) in /_/src/Avalonia.Svg/SvgImageExtension.cs:line 36

```
This does not happen on the latest 0.11 alpha 4

**Comment by wieslawsoltes** [comment]
Well there have been numerous breaking changes to this is expected, I will update this library after next preview.

**Comment by squidink7** [comment]
Ok! I'll close this issue then and reopen if need be if it's still broken after alpha 5
