### ISSUE TITLE
Exception on Linux - Could not load file or assembly Avalonia.Visuals Version=0.10.18.0

### ISSUE THREAD

**Issue by sandreas** [wieslawsoltes/Svg.Skia#142]
Hey there,

I tried to use SVG images in an AvaloniaUI cross platform project and could not use the helpers because of an exception (see below). Am I doing something wrong? I did not find any nuget dependency `Avalonia.Visuals`...

Help would be really appreciated.

Thanks.

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Avalonia.Visuals, Version=0.10.18.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'. The system cannot find the file specified.

File name: 'Avalonia.Visuals, Version=0.10.18.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'
   at Avalonia.Svg.SvgImageExtension.ProvideValue(IServiceProvider serviceProvider)
   at toneUI.Views.MainView.!XamlIlPopulate(IServiceProvider, MainView) in /home/sandreas/projects/toneUI/toneUI/toneUI/Views/MainView.axaml:line 27
   at toneUI.Views.MainView.!XamlIlPopulateTrampoline(MainView)
   at toneUI.Views.MainView.InitializeComponent(Boolean loadXaml) in /home/sandreas/projects/toneUI/toneUI/toneUI/Avalonia.NameGenerator/Avalonia.NameGenerator.AvaloniaNameSourceGenerator/toneUI.Views.MainView.g.cs:line 22
   at toneUI.Views.MainView..ctor() in /home/sandreas/projects/toneUI/toneUI/toneUI/Views/MainView.axaml.cs:line 9
   at toneUI.Views.MainWindow.!XamlIlPopulate(IServiceProvider, MainWindow) in /home/sandreas/projects/toneUI/toneUI/toneUI/Views/MainWindow.axaml:line 11
   at toneUI.Views.MainWindow.!XamlIlPopulateTrampoline(MainWindow)
   at toneUI.Views.MainWindow.InitializeComponent(Boolean loadXaml, Boolean attachDevTools) in /home/sandreas/projects/toneUI/toneUI/toneUI/Avalonia.NameGenerator/Avalonia.NameGenerator.AvaloniaNameSourceGenerator/toneUI.Views.MainWindow.g.cs:line 23
   at toneUI.Views.MainWindow..ctor() in /home/sandreas/projects/toneUI/toneUI/toneUI/Views/MainWindow.axaml.cs:line 9
   at toneUI.App.OnFrameworkInitializationCompleted() in /home/sandreas/projects/toneUI/toneUI/toneUI/App.axaml.cs:line 20
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 289
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 148
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at toneUI.Desktop.Program.Main(String[] args) in /home/sandreas/projects/toneUI/toneUI/toneUI.Desktop/Program.cs:line 13

```

**Comment by wieslawsoltes** [comment]
What version of library do you use and what version of Avalonia, those have to be same

**Comment by sandreas** [comment]
Thank you very much...! Awesome work, man. 
I'm an Idiot and was using 11.0-preview4 with 0.10.18 of svg... 

Now `<Image>` works as expected, but can I also use `<ImageBrush>` somehow? (I can submit another issue, if you'd like)

```xml
      <Border Grid.Row="0" Grid.Column="0" Background="Red" BorderBrush="Black" BorderThickness="2">
        <StackPanel >
          <StackPanel.Background>
                <ImageBrush Source="{SvgImage /Assets/Icons/marble.svg}" />
          </StackPanel.Background>
          <Label Content="Hello"></Label>  
        </StackPanel>
      </Border>
```

```
Unhandled exception. System.InvalidCastException: Specified cast is not valid.
   at toneUI.Views.MainView.DynamicSetters_22.DynamicSetter_1(ImageBrush, Object)
   at toneUI.Views.MainView.!XamlIlPopulate(IServiceProvider, MainView) in /home/sandreas/projects/toneUI/toneUI/toneUI/Views/MainView.axaml:line 27
   at toneUI.Views.MainView.!XamlIlPopulateTrampoline(MainView)
   at toneUI.Views.MainView.InitializeComponent(Boolean loadXaml) in /home/sandreas/projects/toneUI/toneUI/toneUI/Avalonia.NameGenerator/Avalonia.NameGenerator.AvaloniaNameSourceGenerator/toneUI.Views.MainView.g.cs:line 22
   at toneUI.Views.MainView..ctor() in /home/sandreas/projects/toneUI/toneUI/toneUI/Views/MainView.axaml.cs:line 9
   at toneUI.Views.MainWindow.!XamlIlPopulate(IServiceProvider, MainWindow) in /home/sandreas/projects/toneUI/toneUI/toneUI/Views/MainWindow.axaml:line 11
   at toneUI.Views.MainWindow.!XamlIlPopulateTrampoline(MainWindow)
   at toneUI.Views.MainWindow.InitializeComponent(Boolean loadXaml, Boolean attachDevTools) in /home/sandreas/projects/toneUI/toneUI/toneUI/Avalonia.NameGenerator/Avalonia.NameGenerator.AvaloniaNameSourceGenerator/toneUI.Views.MainWindow.g.cs:line 23
   at toneUI.Views.MainWindow..ctor() in /home/sandreas/projects/toneUI/toneUI/toneUI/Views/MainWindow.axaml.cs:line 9
   at toneUI.App.OnFrameworkInitializationCompleted() in /home/sandreas/projects/toneUI/toneUI/toneUI/App.axaml.cs:line 20
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 289
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 148
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at toneUI.Desktop.Program.Main(String[] args) in /home/sandreas/projects/toneUI/toneUI/toneUI.Desktop/Program.cs:line 13

```

**Comment by sandreas** [comment]
@wieslawsoltes 
Just wanted to ask: What about `StackPanel.Background` and `ImageBrush` - what am I doing wrong here?

**Comment by wieslawsoltes** [comment]
ImageBrush is not supported.

**Comment by sandreas** [comment]
thanks for the response.
