### ISSUE TITLE
Exception in the Load function on iOS

### ISSUE THREAD

**Issue by Grzesik** [wieslawsoltes/Svg.Skia#252]
I use the library to show sag in .NET MAUI (9):

 ```
view.svg = new SKSvg();

using (var stream = new MemoryStream(view.data))
{
    view.svg.Load(stream);
}
```

In Android it works very well, but in iOS I receive in the Load function an exception.

I use following nugget packages:

"SkiaSharp.Views.Maui.Controls" Version="3.116.1" 
"Svg.Skia" Version="2.0.0.4" 

Here is the exception stack:

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKColorSpace' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
 ---> System.InvalidOperationException: The version of the native libSkiaSharp library (88.1) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [116.0, 117.0).
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
   at SkiaSharp.SKObject..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKPaint..ctor(IntPtr handle, Boolean owns)
   at SkiaSharp.SKPaint..ctor()
   at Museum2go.Controls.FloorLevelButton..ctor() in /Users/mariangrzesik/Git/museum2go/Museum2goMaui/Museum2go/Controls/FloorLevelButton.cs:line 31
   at System.Object.InvokeStub_FloorLevelButton..ctor(Object , Object , IntPtr* )
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at Svg.Skia.SKSvgSettings..ctor() in /_/src/Svg.Skia/SKSvgSettings.cs:line 24
   at Svg.Skia.SKSvg..ctor() in /_/src/Svg.Skia/SKSvg.Model.cs:line 104
   at Museum2go.Controls.SvgImageView.LoadData(BindableObject bindable, Object oldValue, Object newValue) in /Users/mariangrzesik/Git/museum2go/Museum2goMaui/Museum2go/Controls/SvgImageView.xaml.cs:line 172
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply() in /Users/builder/azdo/_work/5/s/xamarin-macios/src/Foundation/NSAction.cs:line 179
   at Foundation.NSAsyncSynchronizationContextDispatcher.__Registrar_Callbacks__.callback_1412_Foundation_NSAsyncSynchronizationContextDispatcher_Apply(IntPtr pobj, IntPtr sel, IntPtr* exception_gchandle)
--- End of stack trace from previous location ---
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 2719
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/UIKit/UIApplication.cs:line 64
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96
   at Museum2go.Program.Main(String[] args) in /Users/mariangrzesik/Git/museum2go/Museum2goMaui/Museum2go/Platforms/iOS/Program.cs:line 12
2024-12-07 15:16:12.908 Museum2go[9503:6950003] Unhandled managed exception: The type initializer for 'SkiaSharp.SKColorSpace' threw an exception. (System.TypeInitializationException)
   at Svg.Skia.SKSvgSettings..ctor() in /_/src/Svg.Skia/SKSvgSettings.cs:line 24
   at Svg.Skia.SKSvg..ctor() in /_/src/Svg.Skia/SKSvg.Model.cs:line 104
   at Museum2go.Controls.SvgImageView.LoadData(BindableObject bindable, Object oldValue, Object newValue) in /Users/mariangrzesik/Git/museum2go/Museum2goMaui/Museum2go/Controls/SvgImageView.xaml.cs:line 172
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply() in /Users/builder/azdo/_work/5/s/xamarin-macios/src/Foundation/NSAction.cs:line 179
   at Foundation.NSAsyncSynchronizationContextDispatcher.__Registrar_Callbacks__.callback_1412_Foundation_NSAsyncSynchronizationContextDispatcher_Apply(IntPtr pobj, IntPtr sel, IntPtr* exception_gchandle)
--- End of stack trace from previous location ---
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 2719
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/UIKit/UIApplication.cs:line 64
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/5/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96
   at Museum2go.Program.Main(String[] args) in /Users/mariangrzesik/Git/museum2go/Museum2goMaui/Museum2go/Platforms/iOS/Program.cs:line 12
The type initializer for 'SkiaSharp.SKObject' threw an exception. (System.TypeInitializationException)
   at SkiaSharp.SKPaint..ctor(IntPtr handle, Boolean owns)
   at SkiaSharp.SKPaint..ctor()
   at Museum2go.Controls.FloorLevelButton..ctor() in /Users/mariangrzesik/Git/museum2go/Museum2goMaui/Museum2go/Controls/FloorLevelButton.cs:line 31
   at System.Object.InvokeStub_FloorLevelButton..ctor(Object , Object , IntPtr* )
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
The version of the native libSkiaSharp library (88.1) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [116.0, 117.0). (System.InvalidOperationException)
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
   at SkiaSharp.SKObject..cctor()

**Comment by wieslawsoltes** [comment]
It's SkiaSharp version mismatch it's obvious from stack trace. It's not issue with Svg.Skia
